- name: Determine swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

- name: Init Docker Swarm
  shell: >
    docker swarm init 
    --advertise-addr={{ swarm_iface }}:2377
  when: "'inactive' in swarm_status.stdout_lines"
